version: "2"
linters:
  enable:
    - govet
    - staticcheck
    - gosec
    - misspell
    - unconvert
    - unparam
    - errcheck
    - goconst
    - gocyclo
    - gocritic
    - gocyclo
    - gosec
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    # - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

run:
  timeout: 2m
  modules-download-mode: readonly
  build-tags:
    - integration
  tests: false
