version: 2

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar 
    - decorder
    - depguard
    - dogsled 
    - dupl 
    - dupword 
  settings:
    depguard:
      rules:
      # Name of a rule.
        main:
          list-mode: lax
          files:
            - "!**/*_a _file.go"
          allow:
            - $gostd
            - github.com/urfave/cli
            - blog-server/internal/config
            - blog-server/internal/logger
            - blog-server/internal/version
            - blog-server/router

run:
  timeout: 2m
  modules-download-mode: readonly
  build-tags:
    - integration
  tests: false
